#!/bin/sh

psffixffglifs -p checkfix=fix source/masters/Namdhinggo-Regular.ufo         -l source/logs/fixff.log  &
psffixffglifs -p checkfix=fix source/masters/Namdhinggo-ExtraBold.ufo       -l source/logs/fixff.log  &
#psffixffglifs -p checkfix=fix source/masters/Namdhinggo-Italic.ufo          -l source/logs/fixff.log  &
#psffixffglifs -p checkfix=fix source/masters/Namdhinggo-ExtraBoldItalic.ufo -l source/logs/fixff.log  &

./preflight
