#!/bin/sh

psfnormalize -p checkfix=fix source/NamdhinggoSIL-Regular.ufo
psfmakewoffmetadata -n NamdhinggoSIL -i org.sil.fonts source/NamdhinggoSIL-Regular.ufo
psfmakefea -o source/NamdhinggoSIL-Regular.ufo/features.fea -i source/master.feax source/NamdhinggoSIL-Regular.ufo
