#!/bin/sh

# This normalization will also run check and fix routines
psfnormalize -p checkfix=fix source/NamdhinggoSIL-Regular.ufo

# Apply glyph data to Regular UFO
psfsetglyphorder --header sort_final -i source/glyph_data.csv source/NamdhinggoSIL-Regular.ufo

# Create WOFF metadata file
psfmakewoffmetadata -n NamdhinggoSIL -i org.sil.fonts source/NamdhinggoSIL-Regular.ufo # --populateufowoff --force

# Update FEA in UFO
# psfmakefea -o source/NamdhinggoSIL-Regular.ufo/features.fea -i source/master.feax source/NamdhinggoSIL-Regular.ufo
