#!/bin/sh

# Produce individual UFOs from Glyphs files
psfglyphs2ufo --nofea source/masters/Namdhinggo.glyphs source/masters

# This normalization will also run check and fix routines
# psfnormalize -p checkfix=fix source/masters/Namdhinggo-Regular.ufo &
# psfnormalize -p checkfix=fix source/masters/Namdhinggo-ExtraBold.ufo &
# wait

# Fix problem with non-spacing marks due to glyphsLib bug
psfremovegliflibkeys source/masters/Namdhinggo-Regular.ufo   com.schriftgestaltung.Glyphs.originalWidth  -l source/logs/widthfixR.log
psfremovegliflibkeys source/masters/Namdhinggo-ExtraBold.ufo com.schriftgestaltung.Glyphs.originalWidth  -l source/logs/widthfixR.log

./preflight
